name: Release

on:
  workflow_dispatch:
  
env:
  application: app1

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Shell Script
        run: |
          echo "Welcome"
